name: Delete Packages

on:
  push:
    branches:
      - 'workflows'

jobs:
    delete_base:
        runs-on: ubuntu-latest
        
        env:
            VERSION: "SNAPSHOT"

        steps:

            - name: Checkout the code
              uses: actions/checkout@v3

            - name: Update POM Version
              run: |
                echo "Updating to version: ${VERSION}"
                mvn versions:set -DnewVersion=${VERSION}

            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
    
            - name: Setup Maven settings.xml
              uses: whelk-io/maven-settings-xml-action@v20
              with:
                
                repositories: >
                [
                    {
                    "id": "maven",
                    "name": "Maven Central",
                    "url": "https://repo1.maven.org/maven2"
                    },
                    {
                    "id": "github",
                    "name": "Assimbly Base Repository",
                    "url": "https://maven.pkg.github.com/assimbly/base",
                    "snapshots": {
                        "enabled": "true"
                    }
                    },
                    {
                    "id": "github",
                    "name": "Assimbly Runtime Repository",
                    "url": "https://maven.pkg.github.com/assimbly/runtime",
                    "snapshots": {
                        "enabled": "true"
                    }
                    },
                    {
                    "id": "github",
                    "name": "Assimbly Custom-Components Repository",
                    "url": "https://maven.pkg.github.com/assimbly/custom-components",
                    "snapshots": {
                        "enabled": "true"
                    }
                    },
                    {
                    "id": "aurea",
                    "name": "Aurea Sonic Repository",
                    "url": "https://int-factory.aurea.com/nexus/content/repositories/sonic-releases/"
                    }
                ]
    
                servers: >
                [
                    {
                    "id": "github",
                    "username": "$GITHUB_ACTOR",
                    "password": "$GITHUB_TOKEN"
                    }
                ]
    

            - name: Publish to Github Packages
              run: ./gradlew clean publish --settings-file ./settings.gradle -Pprod

            - uses: smartsquaregmbh/delete-old-packages@v0.6.0
              with:
                organization: assimbly
                type: maven
                keep: 2
                version-pattern: "^\\d+\\.\\d+\\.\\d+-SNAPSHOT\\d+$"
                names: |
                    base
                    common-base
                    camel-base
                    spring-base
                    activemq-base
                    test-base
                    database-drivers
                    camel-components
                    utils
                    extra