name: Delete Packages

on:
  push:
    branches:
      - 'workflows'

jobs:
    delete_base:
        runs-on: ubuntu-latest

        steps:

            - name: Checkout the code
              uses: actions/checkout@v3
            
            - name: Get current date
              id: date
              run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

            - name: Update POM Version
              env:
                VERSION: ${{ steps.date.outputs.date }}-SNAPSHOT
              run: |
                echo "Updating to version: ${VERSION}"
                mvn versions:set -DnewVersion=${VERSION}
            
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'temurin'

            - name: Setup Maven settings.xml
              uses: whelk-io/maven-settings-xml-action@v20
              env:
                GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                
                repositories: >
                    [
                        {
                            "id": "maven",
                            "name": "Maven Central",
                            "url": "https://repo1.maven.org/maven2"
                        },
                        {
                            "id": "github",
                            "name": "Assimbly Base Repository",
                            "url": "https://maven.pkg.github.com/assimbly/base",
                            "snapshots": {
                                "enabled": "true"
                            }
                        },
                        {
                            "id": "aurea",
                            "name": "Aurea Sonic Repository",
                            "url": "https://int-factory.aurea.com/nexus/content/repositories/sonic-releases/"
                        }
                    ]
        
                servers: >
                    [
                        {
                            "id": "github",
                            "username": "$GITHUB_ACTOR",
                            "password": "$GITHUB_TOKEN"
                        }
                    ]
            
            - name: Remove HTTP blocker from the built in settings.xml
              run: |
                export MAVEN_PATH=$(mvn -X | grep "home" | head -1 | cut -d " " -f 3)
                echo "this is the path: $MAVEN_PATH"
                echo '<?xml version="1.0" encoding="UTF-8"?>' > "$MAVEN_PATH/conf/settings.xml"
                echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.2.0" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.2.0 https://maven.apache.org/xsd/settings-1.2.0.xsd">' >> "$MAVEN_PATH/conf/settings.xml"
                echo '</settings>' >> "$MAVEN_PATH/conf/settings.xml"
                cat $MAVEN_PATH/conf/settings.xml

            - name: Publish to Github Packages
              run: sh bin/mac/deploy.sh
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - uses: smartsquaregmbh/delete-old-packages@v0.6.0
              with:
                organization: assimbly
                type: maven
                keep: 2
                version-pattern: "^\\d+\\.\\d+\\.\\d+-SNAPSHOT\\d+$"
                names: |
                    base
                    common-base
                    camel-base
                    spring-base
                    activemq-base
                    test-base
                    database-drivers
                    camel-components
                    utils
                    extra