name: Delete Packages

on:
  push:
    branches:
      - 'workflows'

jobs:
    delete_base:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:

            - name: Checkout the code
              uses: actions/checkout@v3
              with:
                ref: "develop"
            
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'temurin'

            - name: Update POM Version
              env:
                VERSION: 4.0.0-SNAPSHOT
              run: |
                  echo "Updating to version: ${VERSION}"
                  mvn versions:set -DnewVersion=${VERSION}

            - name: Delete older snapshots
              uses: smartsquaregmbh/delete-old-packages@v0.7.0
              with:
                organization: assimbly
                type: maven
                keep: 0
                version-pattern: "^\\S+\\-SNAPSHOT$"
                names: |
                  org.assimbly.base
                  org.assimbly.common-base
                  org.assimbly.spring-base
                  org.assimbly.activemq-base
                  org.assimbly.test-base
                  org.assimbly.database-drivers
                  org.assimbly.camel-components
                  org.assimbly.utils
                  org.assimbly.extra