name: Delete Packages

on:
  push:
    branches:
      - 'workflows'

jobs:
    delete_packages:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/delete-package-versions@v4
              with:
                package-name: 'com.assimbly.base'
                package-type: 'maven'
                min-versions-to-keep: 2