name: Publish package to GitHub Packages
on:
  release:
    types: [ released ]
  push:
    branches:
      - 'snapshots-tests'

jobs:

  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    
    steps:
      
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.GITHUB_ACTOR }}
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}