name: Finish Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use'
        default: 'develop'
        type: string
      milestone:
        description: 'Milestone to use as version'
        type: string

  workflow_call:
    inputs:
      branch:
        description: 'Branch to use'
        default: 'develop'
        type: string
      milestone:
        description: 'Milestone to use as version'
        type: string

jobs:

  create-new-branch:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          repository: assimbly/base
          ref: ${{ inputs.branch }}
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: create a new branch
        run: git checkout -b ${{inputs.milestone}}

      - name: Commit files
        run: |
          git config --local user.email "raymondmeester@gmail.com"
          git config --local user.name "skin27"
          git commit -a -m "Update version to ${{inputs.milestone}}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          repository: assimbly/base
          branch: ${{ inputs.milestone }}
          force_with_lease: true

  call-gateway-update-version:
    needs: create-new-branch
    uses: ./.github/workflows/update-version.yml
    secrets: inherit
    with:
      branch: "${{ inputs.milestone }}"
      milestone: "${{ inputs.milestone }}"
