name: Release Snapshots

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 0 * * *'

jobs:
  delete_old_snapshots:

    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:

      - name: Delete older snapshots
        uses: smartsquaregmbh/delete-old-packages@v0.8.1
        with:
          organization: assimbly
          type: maven
          keep: 0
          version-pattern: "^\\S+\\-SNAPSHOT$"
          names: |
            org.assimbly.base
            org.assimbly.common-base
            org.assimbly.camel-base
            org.assimbly.spring-base
            org.assimbly.activemq-base
            org.assimbly.test-base
            org.assimbly.database-drivers
            org.assimbly.camel-components
            org.assimbly.utils
            org.assimbly.extra

  call-release-jars:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-jars.yml
    secrets: inherit
    with:
      branch: 'develop'
