name: Release

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to use'
        default: 'develop'
        type: string

jobs:
  release:

    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:

      - name: Start release
        run: echo "Start release of base"