name: Release Jars

on:
  workflow_dispatch:
  workflow_call:

jobs:
  publish_jar:

    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:

      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          ref: "${{ github.ref_name }}"
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Publish package
        run: mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
