name: Release Jars

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to use'
        default: 'develop'
        type: string

jobs:
  release_jars:

    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:

      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          repository: assimbly/base
          ref: ${{ inputs.branch }}
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Publish package
        run: mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_TOKEN }}
