name: Publish Snapshots

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'snapshots-tests'

jobs:
  delete_old_snapshots:

    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:

      - name: Delete older snapshots
        uses: smartsquaregmbh/delete-old-packages@v0.7.0
        with:
          organization: assimbly
          type: maven
          keep: 0
          version-pattern: "^\\S+\\-SNAPSHOT$"
          names: |
            org.assimbly.base
            org.assimbly.common-base
            org.assimbly.camel-base
            org.assimbly.spring-base
            org.assimbly.activemq-base
            org.assimbly.test-base
            org.assimbly.database-drivers
            org.assimbly.camel-components
            org.assimbly.utils
            org.assimbly.extra

  publish_new_snapshot:
    needs: [delete_old_snapshots]

    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:

      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          ref: "develop"
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Publish package
        run: mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
