name: Update Version Number

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use'
        type: string
        default: 'develop'    
      milestone:
        description: 'Milestone to use as version'
        type: string
        required: true

  workflow_call:
    inputs:
      branch:
        description: 'Branch to use'
        type: string
        default: 'develop'    
      milestone:
        description: 'Milestone to use as version'
        type: string
        required: true

jobs:
  update_version:

    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest

    steps:

      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          repository: assimbly/base
          ref: ${{ inputs.branch }}
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Update POM Version
        run: |
          echo "Updating to version: ${{ inputs.milestone }}"
          mvn versions:set -DnewVersion=${{ inputs.milestone }}
          mvn versions:set-property -Dproperty=assimbly.version -DnewVersion=${{ inputs.milestone }}

      - name: Diff check
        run: git diff

      - name: Commit files
        run: |
          git config --local user.email "raymondmeester@gmail.com"
          git config --local user.name "skin27"
          git diff-index --quiet HEAD || git commit -a -m "Update version to ${{inputs.milestone}}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          repository: assimbly/base
          ref: ${{ inputs.branch }}
          force_with_lease: true
