name: Update Version Number

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to use'
        default: 'develop'
        type: string
      milestone:
        description: 'Milestone to use as version'
        type: string

jobs:
  update_version:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          ref: "${{ inputs.branch }}"

      - name: Update POM Version
        run: |
          echo "Updating to version: ${{ inputs.milestone }}"
          mvn versions:set -DnewVersion=${{ inputs.milestone }}
          mvn versions:set-property -Dproperty=assimbly.version -DnewVersion=${{ inputs.milestone }}

      - name: Diff check
        run: git diff

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: '.'
          default_author: github_actions
          push: "origin HEAD:${{ inputs.branch }} --force"
