name: Update Version Number

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use'
        default: 'develop'
        type: string
      milestone:
        description: 'Milestone to use as version'
        type: string

  workflow_call:
    inputs:
      branch:
        description: 'Branch to use'
        default: 'develop'
        type: string
      milestone:
        description: 'Milestone to use as version'
        type: string

jobs:
  update_version:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:

      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          repository: assimbly/base
          ref: "${{ inputs.branch }}"

      - name: Update POM Version
        run: |
          echo "Show current path"
          pwd
          ls -a
          echo "Updating to version: ${{ inputs.milestone }}"
          mvn versions:set -DnewVersion=${{ inputs.milestone }}
          mvn versions:set-property -Dproperty=assimbly.version -DnewVersion=${{ inputs.milestone }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Diff check
        run: git diff

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Update version to ${{inputs.milestone}}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: assimbly/base
          branch: ${{ inputs.milestone }}
          force: true
